# Generated by Django 5.1.2 on 2024-10-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('atomic_number', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('application', models.TextField()),
                ('fact', models.TextField()),
                ('wiki_link', models.URLField()),
            ],
        ),
    ]
